
create database assemble;
use assemble;


CREATE TABLE modem
(id_modem VARCHAR(50),
Nom_modem VARCHAR(50),
Prénom_modem VARCHAR(50),
Région_modem VARCHAR(50),
Dep_modem VARCHAR(50),
circo_modem VARCHAR(50),
pro_modem VARCHAR(50),
groupe_modem VARCHAR(50)
 );
INSERT INTO modem(id_modem,Nom_modem,Prénom_modem,Région_modem,Dep_modem,circo_modem,pro_modem,groupe_modem)
values
 (1,"Lasserre","Florence","Nouvelle-Aquitaine","Pyrénées-Atlantiques","5","Employée-du-secteur-privé","Démocrate (MoDem et Indépendants)"),
(2,"Falorni","Olivier","Nouvelle-Aquitaine","Charente-Maritime","1","Professeur-du-secondaire","Démocrate (MoDem et Indépendants)"),
(3,"Mandon","Emmanuel","Auvergne-Rhône-Alpes","Loire","3","Conseiller-dinsertion-professionnelle","Démocrate (MoDem et Indépendants)"),
(4,"Lingemann","Delphine","Auvergne-Rhône-Alpes","Puy-de-Dôme","4","Chef-dentreprise","Démocrate (MoDem et Indépendants)"),
(5,"Desjonquères","Mathilde","Centre-Val de Loire","Loir-et-Cher","1","Directrice-Culture-Patrimoine-et-Sport","Démocrate (MoDem et Indépendants)"),
(6,"Daubié","Romain","Auvergne-Rhône-Alpes","Ain","2","Avocat","Démocrate (MoDem et Indépendants)"),
(7,"Balanant","Erwan","Bretagne","Finistère","8","Photographe et réalisateur","Démocrate (MoDem et Indépendants)"),
(8,"Cubertafon","Jean-Pierre","Nouvelle-Aquitaine","Dordogne","3","Retraité des professions libérales","Démocrate (MoDem et Indépendants)"),
(9,"Ott","Hubert","Grand Est","Haut-Rhin","2","Professeur-scientifique","Démocrate (MoDem et Indépendants)"),
(10,"Cosson","Mickaël","Bretagne","Côtes-dArmor","1","Chargé-dopérationsurbanisme","Démocrate (MoDem et Indépendants)"),
(11,"Blanchet","Christophe","Normandie","Calvados","4","Commerçant","Démocrate (MoDem et Indépendants)"),
(12,"Brocard","Blandine","Auvergne-Rhône-Alpes","Rhône","5","Employée(secteur privé)","Démocrate (MoDem et Indépendants)"),
(13,"Poueyto","Josy","Nouvelle-Aquitaine","Pyrénées-Atlantiques","1","Rétraitéedelafonctionpublique","Démocrate (MoDem et Indépendants)"),
(14,"Croizier","Laurent","Bourgogne-Franche-Comté","Doubs","1","Professeurdesécoles","Démocrate (MoDem et Indépendants)"),
(15,"Pahun","Jimmy","Bretagne","Morbihan","2","Navigateur","Démocrate (MoDem et Indépendants)"),
(16,"Folest","Estelle","Ile-de-France","Val-dOise","6","Directrice de la communication","Démocrate (MoDem et Indépendants)"),
(17,"Turquois","Nicolas","Nouvelle-Aquitaine","Vienne","4","Agriculteur-propriétaire exploitant","Démocrate (MoDem et Indépendants)"),
(18,"Bergantz","Anne","Ile-de-France","Yvelines","2","Responsable de service social hospitalier","Démocrate (MoDem et Indépendants)"),
 (19,"Latombe","Philippe","Pays de la Loire","Vendée","1","Cadre supérieur (secteur privé)","Démocrate (MoDem et Indépendants)"),
 (20,"Jacquier-Laforge","Élodie","Auvergne-Rhône-Alpes","Isère","9","Cadre supérieur (secteur privé)","Démocrate (MoDem et Indépendants)"),
 (21,"Martineau","Éric","Pays de la Loire","Sarthe","3","Agriculteur sur moyenne exploitation","Démocrate (MoDem et Indépendants)"),
 (22,"Mattei","Jean-Paul","Nouvelle-Aquitaine","Pyrénées-Atlantiques","2","Notaire","Démocrate (MoDem et Indépendants)"),
 (23,"Berta","Philippe","Occitanie","Gard","6","Professeur de faculté","Démocrate (MoDem et Indépendants)"),
 (24,"Isaac-Sibille","Cyrille","Auvergne-Rhône-Alpes","Rhône","12","Médecin","Démocrate (MoDem et Indépendants)"),
 (25,"Goulet","Perrine","Bourgogne-Franche-Comté","Nièvre","1","Autre cadre (secteur privé)","Démocrate (MoDem et Indépendants)"),
 (26,"Ramos","Richard","Centre-Val de Loire","Loiret","6","Autre cadre (secteur privé)","Démocrate (MoDem et Indépendants)"),
 (27,"Morel","Louise","Grand Est","Bas-Rhin","6","Cadre administratif et commercial dentreprise","Démocrate (MoDem et Indépendants)"),
 (28,"Lecamp","Pascal","Nouvelle-Aquitaine","Vienne","3","Cadre administratif et commercial dentreprise","Démocrate (MoDem et Indépendants)"),
 (29,"Thillaye","Sabine","Centre-Val de Loire","Indre-et-Loire","5","Ancien Chef dentreprise","Démocrate (MoDem et Indépendants)"),
 (30,"Fuchs","Bruno","Grand Est","Haut-Rhin","6","Chef dentreprise","Démocrate (MoDem et Indépendants)"),
 (31,"Gumbs","Frantz","Saint-Barthélemy et Saint-Martin","Saint-Barthélemy et Saint-Martin","1","Personnel de direction de léducation nationale","Démocrate (MoDem et Indépendants)"),
 (32,"Bru","Vincent","Nouvelle-Aquitaine","Pyrénées-Atlantiques","6","Professeur de faculté","Démocrate (MoDem et Indépendants)"),
 (33,"Babault","Anne-Laure","Nouvelle-Aquitaine","Charente-Maritime","2","Cadre administratif et commercial dentreprise","Démocrate (MoDem et Indépendants)"),
 (34,"Vichnievsky","Laurence","Auvergne-Rhône-Alpes","Puy-de-Dôme","3","Magistrat","Démocrate (MoDem et Indépendants)"),
 (35,"Bourlanges","Jean-Louis","Ile-de-France","Hauts-de-Seine","12","Retraité de la fonction publique","Démocrate (MoDem et Indépendants)"),
 (36,"Luquet","Aude","Ile-de-France","Seine-et-Marne","1","Autre profession","Démocrate (MoDem et Indépendants)"),
 (37,"Gatel","Maud","Ile-de-France","Paris","11","Directrice générale adjointe dune agence de communication","Démocrate (MoDem et Indépendants)"),
 (38,"Bolo","Philippe","Pays de la Loire","Maine-et-Loire","7","Ingénieur","Démocrate (MoDem et Indépendants)"),
 (39,"Vigier","Philippe","Centre-Val de Loire","Eure-et-Loir","4","Biologiste A.I.H.P.","Démocrate (MoDem et Indépendants)"),
 (40,"Lainé","Fabien","Nouvelle-Aquitaine","Landes","1","Cadre commercial bâtiment","Démocrate (MoDem et Indépendants)"),
 (41,"Millienne","Bruno","Ile-de-France","Yvelines","9","Cadre supérieur (secteur privé)","Démocrate (MoDem et Indépendants)"),
 (42,"Josso","Sandrine","Pays de la Loire","Loire-Atlantique","7","Autre profession libérale","Démocrate (MoDem et Indépendants)"),
 (43,"Laqhila","Mohamed","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","11","Expert-Comptable-Commissaire aux Comptes","Démocrate (MoDem et Indépendants)"),
 (44,"Geismar","Luc","Pays de la Loire","Loire-Atlantique","5","Directeur régional des ventes","Démocrate (MoDem et Indépendants)"),
 (45,"Zgainski","Frédéric","Nouvelle-Aquitaine","Gironde","7","Chef dentreprise","Démocrate (MoDem et Indépendants)"),
 (46,"Petit","Maud","Ile-de-France","Val-de-Marne","4","Chargée de ressources humaines","Démocrate (MoDem et Indépendants)"),
 (48,"Esquenet-Goxes","Laurent","Occitanie","Haute-Garonne","10","Informaticien","Démocrate (MoDem et Indépendants)"),
 (49,"Bannier","Géraldine","Pays de la Loire","Mayenne","2","Professeur du secondaire et technique","Démocrate (MoDem et Indépendants)"),
 (50,"Mette","Sophie","Nouvelle-Aquitaine","Gironde","9","Sans profession déclarée","Démocrate (MoDem et Indépendants)"),
 (51,"Petit","Frédéric","Français établis hors de France","Français établis hors de France",7,"Ingénieur","Démocrate (MoDem et Indépendants)"),
 (52,"Ferrari","Marina","Auvergne-Rhône-Alpes","Savoie","1","Cadre administratif et commercial dentreprise","Démocrate (MoDem et Indépendants)");


CREATE TABLE ecolonupes(id_ecolonupes int,Nom_ecolonupes VARCHAR(50),Prénom_ecolonupes VARCHAR(50),Région_ecolonupes VARCHAR(50),Département_ecolonupes VARCHAR(50),circonscription_ecolonupes VARCHAR(50),Profession_ecolonupes VARCHAR(50),GroupE_ecolonupesVARCHAR(50));
INSERT INTO ecolonupes (id_ecolonupes,Nom_ecolonupes,Prénom_ecolonupes,Région_ecolonupes,Département_ecolonupes,circonscription_ecolonupes,Profession_ecolonupes,Groupe_ecolonupes)
values
 (1,"Lucas","Benjamin","Ile-de-France","Yvelines","8","consultant","Écologiste - NUPES"),
 (2,"Thierry","Nicolas","Nouvelle-Aquitaine","Gironde","2","Consultant en développement durable","Écologiste - NUPES"),
 (3,"Garin","Marie-Charlotte","Auvergne-Rhône-Alpes","Rhône","3","Collaboratrice politique en collectivité locale","Écologiste - NUPES"),
 (4,"Iordanoff","Jérémie","Auvergne-Rhône-Alpes","Isère","5","Artiste-peintre","Écologiste - NUPES"),
 (5,"Sas","Eva","Ile-de-France","Paris","8","Cadre supérieur du secteur privé","Écologiste - NUPES"),
 (6,"Laernoes","Julie","Pays de la Loire","Loire-Atlantique","4","Ancien cadre","Écologiste - NUPES"),
 (7,"Raux","Jean-Claude","Pays de la Loire","Loire-Atlantique","6","Professeur, profession scientifique","Écologiste - NUPES"),
 (8,"Fournier","Charles","Centre-Val de Loire","Indre-et-Loire","1","consultant - formateur","Écologiste - NUPES"),
 (9,"Arrighi","Christine","Occitanie","Haute-Garonne","9","Ancien cadre","Écologiste - NUPES"),
 (10,"Belluco","Lisa","Nouvelle-Aquitaine","Vienne","1","Cadre de la fonction publique","Écologiste - NUPES"),
 (11,"Taché","Aurélien","Ile-de-France","Val-DOise","95","Fonctionnaire de catégorie A","Écologiste - NUPES"),
 (12,"Taillé-Polian","Sophie","Ile-de-France","Val-de-Marne","11","Cadre de la fonction publique","Écologiste - NUPES"),
 (13,"Chatelain","Cyrielle","Auvergne-Rhône-Alpes","Isère","2","Cadre de la fonction publique","Écologiste - NUPES"),
 (14,"Bayou","Julien","Ile-de-France","Paris","5","Avocat","Écologiste - NUPES"),
 (15,"Julien-Laferrière","Hubert","Auvergne-Rhône-Alpes","Rhône","2","Professeur certifié de SES","Écologiste - NUPES"),
 (16,"Rousseau","Sandrine","Ile-de-France","Paris","9","Professeur, profession scientifique","Écologiste - NUPES"),
 (17,"Peytavie","Sébastien","Nouvelle-Aquitaine","Dordogne","4","Profession intermédiaire de la santé et du travail social","Écologiste - NUPES"),
 (18,"Regol","Sandra","Grand Est","Bas-Rhin","1","consultant","Écologiste - NUPES"),
 (19,"Pasquini","Francesca","Ile-de-France","Hauts-de-Seine","2","Professeur des écoles, instituteur et assimilé","Écologiste - NUPES"),
 (20,"Batho","Delphine","Nouvelle-Aquitaine","Deux-Sèvres","2","Cadre territorial","Écologiste - NUPES"),
 (21,"Sebaihi","Sabrina","Ile-de-France","Hauts-de-Seine","4","Profession libérale","Écologiste - NUPES"),
 (22,"Pochon","Marie","Auvergne-Rhône-Alpes","Drôme","3","Responsable associative","Écologiste - NUPES");
CREATE TABLE gnupes(id_gnupes INT,Nom_gnupes VARCHAR(50),Prénom-gnupes VARCHAR(50),Région_gnupes VARCHAR(50),Département_gnupes VARCHAR(50),circonscription_gnupes VARCHAR(50),Profession_gunpes VARCHAR(50),Groupe_gnupes VARCHAR(50));
INSERT INTO gnupes(id_gnupes,Nom_gnupes,prénom-gnupes,régoion_gnupes,Département_gnupes,circonscription_gnupes,Profession_gunpes,Groupe_gnupes)
values
 (1,"Dharréville","Pierre","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","13","Employé (secteur privé)","Gauche démocrate et républicaine - NUPES"),
 (2,"Monnet","Yannick","Auvergne-Rhône-Alpes","Allier","1","Cadre de la fonction publique","Gauche démocrate et républicaine - NUPES"),
 (3,"Chailloux","Steve","Polynésie française","Polynésie Française","2","Professeur, profession scientifique","Gauche démocrate et républicaine - NUPES"),
 (4,"Roussel","Fabien","Hauts-de-France","Nord","20","Attaché parlementaire","Gauche démocrate et républicaine - NUPES"),
 (5,"Peu","Stéphane","Ile-de-France","Seine-Saint-Denis","2","Employé","Gauche démocrate et républicaine - NUPES"),
 (6,"Sansu","Nicolas","Centre-Val de Loire","Cher","2","Permanent politique","Gauche démocrate et républicaine - NUPES"),
 (7,"Castor","Jean-Victor","Guyane","Guyane","1","Cadre technique dentreprise","Gauche démocrate et républicaine - NUPES"),
 (8,"Maillot","Frédéric","Réunion","Réunion","6","Intervenant social","Gauche démocrate et républicaine - NUPES"),
 (9,"Lebon","Karine","Réunion","Réunion","2","Professeure des écoles","Gauche démocrate et républicaine - NUPES"),
 (10,"William","Jiovanny","Martinique","Martinique","1","Profession libérale","Gauche démocrate et républicaine - NUPES"),
 (11,"Nadeau","Marcellin","Martinique","Martinique","2","Cadre de la fonction publique","Gauche démocrate et républicaine - NUPES"),
 (12,"Faucillon","Elsa","Ile-de-France","Hauts-de-Seine","1","Employée du secteur privé","Gauche démocrate et républicaine - NUPES"),
 (13,"Le Gayic","Tematai","Polynésie française","Polynésie Française","1","étudiant","Gauche démocrate et républicaine - NUPES"),
 (14,"Wulfranc","Hubert","Normandie","Seine-Maritime","3","Profession rattachée à lenseignement","Gauche démocrate et républicaine - NUPES"),
 (15,"Lecoq","Jean-Paul","Normandie","Seine-Maritime","8","Fonctionnaire de catégorie B","Gauche démocrate et républicaine - NUPES"),
 (16,"Chassaigne","André","Auvergne-Rhône-Alpes","Puy-de-Dôme","5","Retraité de léducation nationale","Gauche démocrate et républicaine - NUPES"),
 (17,"Tellier","Jean-Marc","Hauts-de-France","Pas-de-Calais","3","Ancien cadre","Gauche démocrate et républicaine - NUPES"),
 (18,"Jumel","Sébastien","Normandie","Seine-Maritime","6","Cadre de la fonction publique","Gauche démocrate et républicaine - NUPES"),
 (19,"Bourouaha","Soumya","Ile-de-France","Seine-Saint-Denis","4","Professeure","Gauche démocrate et républicaine - NUPES"),
 (20,"K/Bidi","Emeline","Réunion","Réunion","4","Avocate","Gauche démocrate et républicaine - NUPES"),
 (21,"Rimane","Davy","Guyane","Guyane","2","Technicien","Gauche démocrate et républicaine - NUPES"),
 (22,"Brotherson","Moetai","Polynésie française","Polynésie Française","3","fonctionnaire","Gauche démocrate et républicaine - NUPES");
CREATE TABLE horizons(id_horizons int,Nom_horizons VARCHAR(50),Prénom_horizons VARCHAR(50),Région_horizons VARCHAR(50),Département_horizons VARCHAR(50),circonscription_horizons VARCHAR(50),Profession_horizons VARCHAR(50),Groupe_horizons VARCHAR(50));
INSERT INTO MoDemhorizons (id_horizons,Nom_horizons,Prénom_horizons,Région_horizons,Département_horizons,circonscription_horizons,Profession_horizons,Groupe_horizons)
 
 values
 
 (1,"Christophe","Paul","Hauts-de-France","Nord","14","Fonctionnaire de catégorie A","Horizons et apparentés"),
 (2,"Magnier","Lise","Grand Est","Marne","4","cadre territorial","Horizons et apparentés"),
 (3,"Portarrieu","Jean-François","Occitanie","Haute-Garonne","5","Journaliste","Horizons et apparentés"),
 (4,"Poussier-Winsback","Marie-Agnès","Normandie","Seine-Maritime","9","Enseignante","Horizons et apparentés"),
 (5,"Thiébaut","Vincent","Grand Est","Bas-Rhin","9","Autre cadre (secteur privé)","Horizons et apparentés"),
 (6,"Gérard","Félicie","Hauts-de-France","Nord","7","Contremaître, agent de maîtrise","Horizons et apparentés"),
 (7,"Plassard","Christophe","Nouvelle-Aquitaine","Charente-Maritime","5","Profession libérale","Horizons et apparentés"),
 (8,"Lamirault","Luc","Centre-Val de Loire","Eure-et-Loir","3","chef dentreprise","Horizons et apparentés"),
 (9,"Villiers","André","Bourgogne-Franche-Comté","Yonne","2","Agriculteur-propriétaire exploitant","Horizons et apparentés"),
 (10,"Valletoux","Frédéric","Ile-de-France","Seine-et-Marne","2","Profession de linformation","Horizons et apparentés"),
 (11,"Benoit","Thierry","Bretagne","Ille-et-Vilaine","6","Représentant de commerce","Horizons et apparentés"),
 (12,"Marcangeli","Laurent","Corse","Corse-du-Sud","1","Avocat","Horizons et apparentés"),
 (13,"Violland","Anne-Cécile","Auvergne-Rhône-Alpes","Haute-Savoie","5","Profession libérale","Horizons et apparentés"),
 (14,"Alfandari","Henri","Centre-Val de Loire","Indre-et-Loire","3","Ancien artisan, commerçant, chef dentreprise","Horizons et apparentés"),
 (15,"Favennec-Bécot","Yannick","Pays de la Loire","Mayenne","3","Directeur de cabinet","Horizons et apparentés"),
 (16,"Moutchou","Naïma","Ile-de-France","Val-dOise","4","Avocat","Horizons et apparentés"),
(17,"Albertini","Xavier","Grand Est","Marne","1","Profession libérale","Horizons et apparentés"),
 (18,"Pradal","Philippe","Provence-Alpes-Côte dAzur","Alpes-Maritimes","3","Expert comptable","Horizons et apparentés"),
 (19,"Kochert","Stéphanie","Grand Est","Bas-Rhin","8","Profession intermédiaire de la santé et du travail social","Horizons et apparentés"),
 (20,"Patrier-Leitus","Jérémie","Normandie","Calvados","3","Cadre de la fonction publique","Horizons et apparentés"),
 (21,"Kervran","Loïc","Centre-Val de Loire","Cher","3","Autre cadre (secteur privé)","Horizons et apparentés"),
 (22,"Bellamy","Béatrice","Pays de la Loire","Vendée","2","Cadre administratif et commercial dentreprise","Horizons et apparentés"),
 (23,"Carel","Agnès","Normandie","Seine-Maritime","7","Enseignante","Horizons et apparentés"),
 (24,"Lemaire","Didier","Grand Est","Haut-Rhin","3","Employé civil et agent de service de la fonction publique","Horizons et apparentés"),
 (25,"Le Hénanff","Anne","Bretagne","Morbihan","1","Consultante indépendante","Horizons et apparentés"),
 (26,"Larsonneur","Jean-Charles","Bretagne","Finistère","2","Diplomate","Horizons et apparentés"),
 (27,"Rauch","Isabelle","Grand Est","Moselle","9","Consultante","Horizons et apparentés"),
 (28,"Jolivet","François","Centre-Val de Loire","Indre","1","Cadre supérieur (secteur privé)","Horizons et apparentés"),
 (29,"Gernigon","François","Pays de la Loire","Maine-et-Loire","1","Ancien cadre","Horizons et apparentés");
  
  CREATE TABLE lfi(id_lfi int,Nom _lfi VARCHAR(50),Prénom_lfi VARCHAR(50),Région_lfi VARCHAR(50),Département VARCHAR(50),circonscription_lfi VARCHAR(50),Profession_lfi VARCHAR(10),Groupe_fli VARCHAR(50));
INSERT INTO lfi (id-lfi,Nom_lfi,Prénom_lfi,Région_lfi,Département_lfi,circonscription_lfi,Profession_lfi,Groupe_lfi)
 values    
  (1,"Martinet","William","Ile-de-France","Yvelines","11","Cadre administratif","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (2,"Obono","Danièle","Ile-de-France","Paris","17","Bibliothécaire","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (3,"Boumertit","Idir","Auvergne-Rhône-Alpes","Rhône","14","Employé administratif dentreprise","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (4,"Oziol","Nathalie","Occitanie","Hérault","2","Professeur, profession scientifique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (5,"Chikirou","Sophia","Ile-de-France","Paris","6","Chef dentreprise de 10 salariés ou plus","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (6,"Bernalicis","Ugo","Hauts-de-France","Nord","2","Fonctionnaire de catégorie A","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (7,"Ferrer","Sylvie","Occitanie","Hautes-Pyrénées","1","employé","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (8,"Ruffin","François","Hauts-de-France","Somme","1","Reporter","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (9,"Etienne","Martine","Grand Est","Meurthe-et-Moselle","3","Ancien employé","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (10,"Boyard","Louis","Ile-de-France","Val-de-Marne","3","Elève, étudiant","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (11,"Davi","Hendrik","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","5","Professeur, profession scientifique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (12,"Mathieu","Frédéric","Bretagne","Ille-et-Vilaine","1","Cadre de la fonction publique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (13,"Martin","Élisa","Auvergne-Rhône-Alpes","Isère","3","Professeur, profession scientifique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (14,"Kerbrat","Andy","Pays de la Loire","Loire-Atlantique","2","Chargé dassitance automobile","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (15,"Erodi","Karen","Occitanie","Tarn","2","Profession libérale","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (16,"Rome","Sébastien","Occitanie","Hérault","4","Professeur des écoles, instituteur et assimilé","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (17,"Martin","Pascale","Nouvelle-Aquitaine","Dordogne","1","Ancien cadre","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (18,"Saintoul","Aurélien","Ile-de-France","Hauts-de-Seine","11","Cadre de la fonction publique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (19,"Delogu","Sébastien","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","7","Sans profession","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (20,"Bex","Christophe","Occitanie","Haute-Garonne","7","Cadre de la fonction publique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (21,"Arenas","Rodrigo","Ile-de-France","Paris","10","Cadre de la fonction publique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (22,"Fiat","Caroline","Grand Est","Meurthe-et-Moselle","6","Salariée du secteur médical","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (23,"Amrani","Farida","Ile-de-France","Essonne","1","Cadre de la fonction publique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (24,"Alexandre","Laurent","Occitanie","Aveyron","2","Ouvrier qualifié de type industriel","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (25,"Lachaud","Bastien","Ile-de-France","Seine-Saint-Denis","6","Professeur du secondaire et technique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (26,"Carrière","Sylvain","Occitanie","Hérault","8","Employé de commerce","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (27,"Garrido","Raquel","Ile-de-France","Seine-Saint-Denis","5","Avocate","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (28,"Gaillard","Perceval","Réunion","Réunion","7","Profession intermédiaire de la santé et du travail social","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (29,"Ratenon","Jean-Hugues","Réunion","Réunion","5","Employé (secteur privé)","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (30,"Autain","Clémentine","Ile-de-France","Seine-Saint-Denis","11","Journaliste et autre média","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (31,"Fernandes","Emmanuel","Grand Est","Bas-Rhin","2","Profession intermédiaire administrative et commerciale des entreprises","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (32,"Sala","Michel","Occitanie","Gard","5","Ancien cadre du secteur bancaire","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (33,"Pilato","René","Nouvelle-Aquitaine","Charente","1","Enseignant","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (34,"Bilongo","Carlos Martens","Ile-de-France","Val-dOise","8","Professeur, profession scientifique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (35,"Tavel","Matthias","Pays de la Loire","Loire-Atlantique","8","Cadre de la fonction publique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (36,"Legavre","Jérôme","Ile-de-France","Seine-Saint-Denis","12","Professeur de lettres","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (37,"Taurinya","Andrée","Auvergne-Rhône-Alpes","Loire","2","Professeur, profession scientifique ","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (38,"Walter","Léo","Provence-Alpes-Côte dAzur","Alpes-de-Haute-Provence","2","Directeur décole","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (39,"Guetté","Clémence","Ile-de-France","Val-de-Marne","2","Responsable du programme LFI","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (40,"Maximi","Marianne","Auvergne-Rhône-Alpes","Puy-de-Dôme","1","Profession intermédiaire de la santé et du travail social","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (41,"Legrain","Sarah","Ile-de-France","Paris","16","Professeure de français","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (42,"Stambach-Terrenoir","Anne","Occitanie","Haute-Garonne","2","Sans profession déclarée","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (43,"Dufour","Alma","Normandie","Seine-Maritime","4","Responsable associative","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (44,"Prudhomme","Loïc","Nouvelle-Aquitaine","Gironde","3","Fonctionnaire de catégorie B","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (45,"Bompard","Manuel","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","4","Ingénieur","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (46,"Piquemal","François","Occitanie","Haute-Garonne","4","Enseignant","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (47,"Couturier","Catherine","Nouvelle-Aquitaine","Creuse","1","Ancienne profession intermédiaire","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (48,"Leduc","Charlotte","Grand Est","Moselle","3","Archéozoologue","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (49,"Laisney","Maxime","Ile-de-France","Seine-et-Marne","10","Professeur des écoles, instituteur et assimilé","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (50,"Soudais","Ersilia","Ile-de-France","Seine-et-Marne","7","Professeur, profession scientifique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (51,"Guiraud","David","Hauts-de-France","Nord","8","Cadre administratif dentreprise","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (52,"Chauche","Florian","Bourgogne-Franche-Comté","Territoire de Belfort","2","Fonctionnaire territorial - Agent du service courrier","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (53,"Coulomme","Jean-François","Auvergne-Rhône-Alpes","Savoie","4","Ingénieur commercial","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (54,"Amiot","Ségolène","Pays de la Loire","Loire-Atlantique","3","Employé administratif dentreprise","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (55,"Hignet","Mathilde","Bretagne","Ille-et-Vilaine","4","Ouvrière agricole","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (56,"Vannier","Paul","Ile-de-France","Val-dOise","5","Professeur dhistoire-géographie","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (57,"Coquerel","Éric","Ile-de-France","Seine-Saint-Denis","1","Industriel-Chef dentreprise","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (58,"Corbière","Alexis","Ile-de-France","Seine-Saint-Denis","7","Professeur de lycée professionnel","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (59,"Portes","Thomas","Ile-de-France","Seine-Saint-Denis","3","cheminot","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (60,"Amard","Gabriel","Auvergne-Rhône-Alpes","Rhône","6","Cadre administratif et commercial dentreprise","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (61,"Nilor","Jean-Philippe","Martinique","Martinique","4","Collaborateur parlementaire","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (62,"Abomangoli","Nadège","Ile-de-France","Seine-Saint-Denis","10","Contrôleure interne et risk manager","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (63,"Le Gall","Arnaud","Ile-de-France","Val-dOise","9","Cadre de la fonction publique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (64,"Meunier","Manon","Nouvelle-Aquitaine","Haute-Vienne","3","Cadre de la fonction publique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (65,"Lepvraud","Murielle","Bretagne","Côtes-dArmor","4","Employé administratif dentreprise","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (66,"Maudet","Damien","Nouvelle-Aquitaine","Haute-Vienne","1","Cadre administratif et commercial dentreprise","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (67,"Léaument","Antoine","Ile-de-France","Essonne","10","Responsable de la communication numérique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (68,"Trouvé","Aurélie","Ile-de-France","Seine-Saint-Denis","9","Cadre de la fonction publique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (69,"Panot","Mathilde","Ile-de-France","Val-de-Marne","10","Coordinatrice de projets associatifs","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (70,"Keke","Rachel","Ile-de-France","Val-de-Marne","7","Personnel des services directs aux particuliers","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (71,"Leboucher","Élise","Pays de la Loire","Sarthe","4","Educatrice spécialisée","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (72,"Simonnet","Danielle","Ile-de-France","Paris","15","Professeur, profession scientifique","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (73,"Caron","Aymeric","Ile-de-France","Paris","18","Profession de linformation, des arts et des spectacles","La France insoumise - Nouvelle Union Populaire écologique et sociale"),
 (74,"Clouet","Hadrien","Occitanie","Haute-Garonne","1","Professeur, profession scientifique","La France insoumise - Nouvelle Union Populaire écologique et sociale");
 
CREATE TABLE lr(id_lr int,Nom_lr VARCHAR(50),Prénom_lr VARCHAR(50),Région VARCHAR(50),Département_lr VARCHAR(50),circonscription_lr VARCHAR(50),Profession_lr VARCHAR(50),Groupe_lr VARCHAR(50));
INSERT INTO lr (id_lr,Nom_lr,Prénom_lr,Région_lr,Département_lr,circonscription_lr,Profession_lr,Groupe_lr)
  values
  (1,"Bazin-Malgras","Valérie","Grand Est","Aube","2","Commerçante","Les Républicains"),
 (2,"Hetzel","Patrick","Grand Est","Bas-Rhin","7","Professeur des Universités","Les Républicains"),
 (3,"Louwagie","Véronique","Normandie","Orne","2","Expert-comptable","Les Républicains"),
 (4,"Valentin","Isabelle","Auvergne-Rhône-Alpes","Haute-Loire","1","Salariée agricole","Les Républicains"),
 (5,"Blin","Anne-Laure","Pays de la Loire","Maine-et-Loire","3","Juriste","Les Républicains"),
 (6,"Vermorel-Marques","Antoine","Auvergne-Rhône-Alpes","Loire","5","Conseiller parlementaire","Les Républicains"),
(7,"Brigand","Hubert","Bourgogne-Franche-Comté","Côte-dOr","4","Ancienne profession intermédiaire","Les Républicains"),
 (8,"Bazin","Thibault","Grand Est","Meurthe-et-Moselle","4","Autre cadre (secteur privé)","Les Républicains"),
 (9,"Ciotti","Éric","Provence-Alpes-Côte dAzur","Alpes-Maritimes","1","cadre","Les Républicains"),
 (10,"Boucard","Ian","Bourgogne-Franche-Comté","Territoire de Belfort","1","Autre cadre (secteur privé)","Les Républicains"),
 (11,"Bonnivard","Émilie","Auvergne-Rhône-Alpes","Savoie","3","Cadre à la Caisse des Dépôts et Consignations","Les Républicains"),
 (12,"Di Filippo","Fabien","Grand Est","Moselle","4","Ancien cadre du secteur privé","Les Républicains"),
 (13,"Corneloup","Josiane","Bourgogne-Franche-Comté","Saône-et-Loire","2","Pharmacien","Les Républicains"),
 (14,"Maquet","Emmanuel","Hauts-de-France","Somme","3","Agent général dassurances","Les Républicains"),
 (15,"Petex-Levet","Christelle","Auvergne-Rhône-Alpes","Haute-Savoie","3","Cadre administratif et commercial dentreprise","Les Républicains"),
 (16,"Martin","Alexandra","Provence-Alpes-Côte dAzur","Alpes-Maritimes","8","Employé civil et agent de service de la fonction publique","Les Républicains"),
 (17,"Gaultier","Jean-Jacques","Grand Est","Vosges","4","Médecin biologiste","Les Républicains"),
 (18,"Dubois","Francis","Nouvelle-Aquitaine","Corrèze","1","Technicien","Les Républicains"),
 (19,"Schellenberger","Raphaël","Grand Est","Haut-Rhin","4","Attaché Parlementaire","Les Républicains"),
 (20,"Habert-Dassault","Victor","Hauts-de-France","Oise","1","Avocat","Les Républicains"),
 (21,"Le Fur","Marc","Bretagne","Côtes-dArmor","3","Sous-préfet","Les Républicains"),
 (22,"Gosselin","Philippe","Normandie","Manche","1","Maître de conférences à Sciences Po","Les Républicains"),
 (23,"Vincendet","Alexandre","Auvergne-Rhône-Alpes","Rhône","7","Elu local","Les Républicains"),
 (24,"Cordier","Pierre","Grand Est","Ardennes","2","Fonctionnaire de catégorie A","Les Républicains"),
 (25,"Juvin","Philippe","Ile-de-France","Hauts-de-Seine","3","Professeur de médecine","Les Républicains"),
 (26,"Dumont","Pierre-Henri","Hauts-de-France","Pas-de-Calais","7","Collaborateur parlementaire","Les Républicains"),
 (27,"Neuder","Yannick","Auvergne-Rhône-Alpes","Isère","7","Cardiologue","Les Républicains"),
 (28,"Viry","Stéphane","Grand Est","Vosges","1","Avocat","Les Républicains"),
 (29,"Ray","Nicolas","Auvergne-Rhône-Alpes","Allier","3","Inspecteur principal des Finances publiques","Les Républicains"),
 (30,"Bony","Jean-Yves","Auvergne-Rhône-Alpes","Cantal","2","Exploitant agricole","Les Républicains"),
 (31,"Kamardine","Mansour","Mayotte","Mayotte","2","Avocat","Les Républicains"),
 (32,"Portier","Alexandre","Auvergne-Rhône-Alpes","Rhône","9","Professeur, profession scientifique","Les Républicains"),
 (33,"Vatin","Pierre","Hauts-de-France","Oise","5","Permanent politique","Les Républicains"),
 (34,"Anthoine","Emmanuelle","Auvergne-Rhône-Alpes","Drôme","4","Avocate","Les Républicains"),
 (35,"Minot","Maxime","Hauts-de-France","Oise","7","Employé (secteur privé)","Les Républicains"),
 (36,"Herbillon","Michel","Ile-de-France","Val-de-Marne","8","Cadre supérieur","Les Républicains"),
 (37,"Taite","Jean-Pierre","Auvergne-Rhône-Alpes","Loire","6","Ancien artisan, commerçant, chef dentreprise","Les Républicains"),
 (38,"Cinieri","Dino","Auvergne-Rhône-Alpes","Loire","4","Consultant sécurité","Les Républicains"),
 (39,"Gruet","Justine","Bourgogne-Franche-Comté","Jura","3","Masseur Kinésithérapeute","Les Républicains"),
 (40,"DIntorni","Christelle","Provence-Alpes-Côte dAzur","Alpes-Maritimes","5","Avocate","Les Républicains"),
 (41,"Vigier","Jean-Pierre","Auvergne-Rhône-Alpes","Haute-Loire","2","Fonctionnaire de catégorie A","Les Républicains"),
 (42,"Rolland","Vincent","Auvergne-Rhône-Alpes","Savoie","2","Collaborateur parlementaire","Les Républicains"),
 (43,"Nury","Jérôme","Normandie","Orne","3","Cadre de la fonction publique","Les Républicains"),
 (44,"Seitlinger","Vincent","Grand Est","Moselle","5","Notaire","Les Républicains"),
 (45,"Pauget","Éric","Provence-Alpes-Côte dAzur","Alpes-Maritimes","7","Autre cadre (secteur privé)","Les Républicains"),
 (46,"Breton","Xavier","Auvergne-Rhône-Alpes","Ain","1","Cadre territorial","Les Républicains"),
 (47,"Brun","Fabrice","Auvergne-Rhône-Alpes","Ardèche","3","Industriel-Chef dentreprise","Les Républicains"),
 (48,"Périgault","Isabelle","Ile-de-France","Seine-et-Marne","4","Directrice administrative","Les Républicains"),
 (49,"Tabarot","Michèle","Provence-Alpes-Côte dAzur","Alpes-Maritimes","9","Chef dentreprise","Les Républicains"),
 (50,"Marleix","Olivier","Centre-Val de Loire","Eure-et-Loir","2","Fonctionnaire de catégorie A","Les Républicains"),
 (51,"Forissier","Nicolas","Centre-Val de Loire","Indre","2","Chef dentreprise","Les Républicains"),
 (52,"Duby-Muller","Virginie","Auvergne-Rhône-Alpes","Haute-Savoie","4","Cadre du secteur privé","Les Républicains"),
 (53,"Meunier","Frédérique","Nouvelle-Aquitaine","Corrèze","2","Avocate","Les Républicains"),
 (54,"Descoeur","Vincent","Auvergne-Rhône-Alpes","Cantal","1","Professeur agrégé de biologie","Les Républicains"),
 (55,"Thiériot","Jean-Louis","Ile-de-France","Seine-et-Marne","3","Avocat","Les Républicains"),
 (56,"Bourgeaux","Jean-Luc","Bretagne","Ille-et-Vilaine","7","Agriculteur","Les Républicains"),
 (57,"Dive","Julien","Hauts-de-France","Aisne","2","Chef de projet dans lindustrie","Les Républicains"),
 (58,"Pradié","Aurélien","Occitanie","Lot","1","Cadre supérieur (secteur privé)","Les Républicains"),
 (59,"Serre","Nathalie","Auvergne-Rhône-Alpes","Rhône","8","Mère au foyer","Les Républicains"),
 (60,"Dalloz","Marie-Christine","Bourgogne-Franche-Comté","Jura","2","employé","Les Républicains"),
 (61,"Genevard","Annie","Bourgogne-Franche-Comté","Doubs","5","Professeur du secondaire","Les Républicains");
 CREATE TABLE liot(id_liot int,Nom_liot VARCHAR(50),Prénom_liot VARCHAR(50),Région_liot VARCHAR(50),Département_liot VARCHAR(50),circonscription_liot VARCHAR(50),Profession-liot VARCHAR(50),Groupe_liot VARCHAR(50));
INSERT INTO liot (id_liot,Nom_liot,Prénom-liot,Région_liot,Département_liot,circonscription_liot,Profession_liot,Groupe_liot)

 values
 
 (1,"Acquaviva","Jean-Félix","Corse","Haute-Corse","2","Cadre","Libertés, Indépendants, Outre-mer et Territoires"),
 (2,"Mathiasin","Max","Guadeloupe","Guadeloupe","3","Fonction publique territoriale","Libertés, Indépendants, Outre-mer et Territoires"),
 (3,"Bricout","Guy","Hauts-de-France","Nord","18","Retraité fonction publique (hors enseignement)","Libertés, Indépendants, Outre-mer et Territoires"),
 (4,"Molac","Paul","Bretagne","Morbihan","4","Professeur du secondaire","Libertés, Indépendants, Outre-mer et Territoires"),
 (5,"Castellani","Michel","Corse","Haute-Corse","1","Professeur des Universités","Libertés, Indépendants, Outre-mer et Territoires"),
 (6,"Naegelen","Christophe","Grand Est","Vosges","3","Industriel-Chef dentreprise","Libertés, Indépendants, Outre-mer et Territoires"),
 (7,"Morel-À-LHuissier","Pierre","Occitanie","Lozère","1","Avocat","Libertés, Indépendants, Outre-mer et Territoires"),
(8,"Bricout","Jean-Louis","Hauts-de-France","Aisne","3","Cadre (secteur privé)","Libertés, Indépendants, Outre-mer et Territoires"),
 (9,"Lenormand","Stéphane","Saint-Pierre-et-Miquelon","Saint-Pierre-et-Miquelon","1","Ancien cadre","Libertés, Indépendants, Outre-mer et Territoires"),
 (10,"Saint-Huile","Benjamin","Hauts-de-France","Nord","3","Chargé de mission","Libertés, Indépendants, Outre-mer et Territoires"),
 (11,"de Courson","Charles","Grand Est","Marne","5","Conseiller référendaire honoraire à la Cour des comptes","Libertés, Indépendants, Outre-mer et Territoires"),
 (12,"Serva","Olivier","Guadeloupe","Guadeloupe","1","Expert comptable","Libertés, Indépendants, Outre-mer et Territoires"),
 (13,"Pancher","Bertrand","Grand Est","Meuse","1","Directeur du développement","Libertés, Indépendants, Outre-mer et Territoires"),
 (14,"Descamps","Béatrice","Hauts-de-France","Nord","21","Enseignant 1er deg.-directeur école","Libertés, Indépendants, Outre-mer et Territoires"),
 (15,"Warsmann","Jean-Luc","Grand Est","Ardennes","3","Directeur de mutuelle","Libertés, Indépendants, Outre-mer et Territoires"),
 (16,"Colombani","Paul-André","Corse","Corse-du-Sud","2","Médecin","Libertés, Indépendants, Outre-mer et Territoires"),
 (17,"Panifous","Laurent","Occitanie","Ariège","2","Directeur détablissements sanitaires et sociaux","Libertés, Indépendants, Outre-mer et Territoires"),
 (18,"Youssouffa","Estelle","Mayotte","Mayotte","1","Consultante","Libertés, Indépendants, Outre-mer et Territoires"),
 (19,"Taupiac","David","Occitanie","Gers","2","Consultant aéronautique","Libertés, Indépendants, Outre-mer et Territoires"),
 (20,"Bassire","Nathalie","Réunion","Réunion","3","Retraitée de lenseignement","Libertés, Indépendants, Outre-mer et Territoires");
 CREATE TABLE ni(id_ni int,Nom_ni VARCHAR(50),Prénom_ni VARCHAR(50),Région_ni VARCHAR(50),Département_ni VARCHAR(50),circonscription_ni VARCHAR(50),Profession-ni VARCHAR(50),Groupe_ni VARCHAR(50));
INSERT INTO ni (id-ni,Nom_ni,Prénom_ni,Région_ni,Département_ni,circonscription_ni,Profession_ni,Groupe_ni)
 values
 (1,"Ménard","Emmanuelle","Occitanie","Hérault","6","Journaliste et autre média","Non inscrit"),
 (2,"Besse","Véronique","Pays de la Loire","Vendée","4","Journaliste","Non inscrit"),
 (3,"Quatennens","Adrien","Hauts-de-France","Nord","1","Employé (secteur privé)","Non inscrit"),
 (4,"Dupont-Aignan","Nicolas","Ile-de-France","Essonne","8","Administrateur de lEtat","Non inscrit"),
 (5,"Habib","David","Nouvelle-Aquitaine","Pyrénées-Atlantiques","3","Cadre","Non inscrit");

CREATE TABLE rn(id_rn int,Nom_rn VARCHAR(50),Prénom_rn VARCHAR(50),Région_rn VARCHAR(50),Département_rn VARCHAR(50),circonscription_rn VARCHAR(50),Profession_rn VARCHAR(50),Groupe_rn VARCHAR(50));
INSERT INTO rn(id_rn,Nom_rn,Prénom_rn,Région_rn,Département_rn,circonscription_rn,Profession_rn,Groupe_rn)
 values
 (1,"Levavasseur","Katiana","Normandie","Eure","2","Ouvrier de type industriel","Rassemblement National"),
 (2,"Colombier","Caroline","Nouvelle-Aquitaine","Charente","3","Avocate / Ancien cadre ","Rassemblement National"),
 (3,"Bilde","Bruno","Hauts-de-France","Pas-de-Calais","12","Juriste","Rassemblement National"),
 (4,"Loir","Christine","Normandie","Eure","1","Profession intermédiaire de la santé et du travail social","Rassemblement National"),
 (5,"Marchio","Matthieu","Hauts-de-France","Nord","16","Cadre administratif et commercial dentreprise","Rassemblement National"),
 (6,"Masson","Alexandra","Provence-Alpes-Côte dAzur","Alpes-Maritimes","4","Profession libérale","Rassemblement National"),
 (7,"Rambaud","Stéphane","Provence-Alpes-Côte dAzur","Var","3","Retraité de la police nationale","Rassemblement National"),
 (8,"Barthès","Christophe","Occitanie","Aude","1","Agriculteur sur moyenne exploitation","Rassemblement National"),
 (9,"Masson","Bryan","Provence-Alpes-Côte dAzur","Alpes-Maritimes","6","Profession intermédiaire administrative de la fonction publique","Rassemblement National"),
 (10,"Rancoule","Julien","Occitanie","Aude","3","Profession libérale","Rassemblement National"),
 (11,"Giletti","Frank","Provence-Alpes-Côte dAzur","Var","6","Fonctionnaire","Rassemblement National"),
 (12,"Salmon","Emeric","Bourgogne-Franche-Comté","Haute-Saône","2","Cadre administratif et commercial dentreprise","Rassemblement National"),
 (13,"Hébrard","Joris","Provence-Alpes-Côte dAzur","Vaucluse","1","Profession libérale","Rassemblement National"),
 (14,"Schreck","Philippe","Provence-Alpes-Côte dAzur","Var","8","Profession libérale ","Rassemblement National"),
 (15,"Blanc","Sophie","Occitanie","Pyrénées-Orientales","1","Profession libérale","Rassemblement National"),
 (16,"Lorho","Marie-France","Provence-Alpes-Côte dAzur","Vaucluse","4","Déléguée médicale","Rassemblement National"),
 (17,"Blairy","Emmanuel","Hauts-de-France","Pas-de-Calais","1","Fonctionnaire territorial","Rassemblement National"),
 (18,"de Lépinau","Hervé","Provence-Alpes-Côte dAzur","Vaucluse","3","Avocat","Rassemblement National"),
 (19,"Goulet","Florence","Grand Est","Meuse","2","Cadre de la fonction publique","Rassemblement National"),
 (20,"Meizonnet","Nicolas","Occitanie","Gard","2","Ingénieur en informatique ","Rassemblement National"),
 (21,"Martinez","Michèle","Occitanie","Pyrénées-Orientales","4","Sans profession déclarée","Rassemblement National"),
 (22,"Menache","Yaël","Hauts-de-France","Somme","5","Commerciale","Rassemblement National"),
 (23,"Pfeffer","Kévin","Grand Est","Moselle","6","Permanent politique","Rassemblement National"),
 (24,"Bentz","Christophe","Grand Est","Haute-Marne","1","Professeur, profession scientifique","Rassemblement National"),
 (25,"Chudeau","Roger","Centre-Val de Loire","Loir-et-Cher","2","Inspecteur général de léducation nationale honoraire ","Rassemblement National"),
 (26,"Buisson","Jérôme","Auvergne-Rhône-Alpes","Ain","4","Professeur ditalien","Rassemblement National"),
 (27,"Jacobelli","Laurent","Grand Est","Moselle","8","Profession de linformation, des arts et des spectacles","Rassemblement National"),
 (28,"Ménagé","Thomas","Centre-Val de Loire","Loiret","4","Cadre administratif et commercial dentreprise","Rassemblement National"),
 (29,"Mélin","Joëlle","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","9","Médecin expert judiciaire","Rassemblement National"),
 (30,"Dragon","Nicolas","Hauts-de-France","Aisne","1","Profession libérale","Rassemblement National"),
 (31,"Meurin","Pierre","Occitanie","Gard","4","Cadre administratif et commercial dentreprise","Rassemblement National"),
 (32,"Grangier","Géraldine","Bourgogne-Franche-Comté","Doubs","4","Profession intermédiaire administrative de la fonction publique","Rassemblement National"),
 (33,"Sabatou","Alexandre","Hauts-de-France","Oise","3","Chef de projets SI","Rassemblement National"),
 (34,"Parmentier","Caroline","Hauts-de-France","Pas-de-Calais","9","Attachée de Presse","Rassemblement National"),
 (35,"Pollet","Lisette","Auvergne-Rhône-Alpes","Drôme","2","Ouvrier qualifié de type industriel","Rassemblement National"),
 (36,"Lelouis","Gisèle","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","3","Ancien employé ","Rassemblement National"),
 (37,"Le Pen","Marine","Hauts-de-France","Pas-de-Calais","11","Avocate","Rassemblement National"),
 (38,"Allisio","Franck","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","12","Profession libérale","Rassemblement National"),
 (39,"Guitton","Jordan","Grand Est","Aube","1","Assistant Parlementaire","Rassemblement National"),
 (40,"Berteloot","Pierrick","Hauts-de-France","Nord","15","Assistant Maitre dÉquipage - Assistant Toutes Catégories","Rassemblement National"),
 (41,"Diaz","Edwige","Nouvelle-Aquitaine","Gironde","11","Cadre administratif et commercial dentreprise","Rassemblement National"),
 (42,"Taché de la Pagerie","Emmanuel","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","16","Cadre de la fonction publique","Rassemblement National"),
 (43,"Ranc","Angélique","Grand Est","Aube","3","Sans activité professionnelle","Rassemblement National"),
 (44,"Dessigny","Jocelyn","Hauts-de-France","Aisne","5","Cadre administratif et commercial dentreprise","Rassemblement National"),
(45,"Bovet","Jorys","Auvergne-Rhône-Alpes","Allier","2","Chauffeur-livreur","Rassemblement National"),
 (46,"Lechanteux","Julie","Provence-Alpes-Côte dAzur","Var","5","cadre","Rassemblement National"),
 (47,"Villedieu","Antoine","Bourgogne-Franche-Comté","Haute-Saône","1","Policier","Rassemblement National"),
 (48,"Mauvieux","Kévin","Normandie","Eure","3","Conseiller en assurance","Rassemblement National"),
 (49,"Cabrolier","Frédéric","Occitanie","Tarn","1","Conseiller protection sociale (Assurances)","Rassemblement National"),
 (50,"Hamelet","Marine","Occitanie","Tarn-et-Garonne","2","Profession intermédiaire administrative et commerciale des entreprises ","Rassemblement National"),
 (51,"François","Thibaut","Hauts-de-France","Nord",17,"Cadre de la fonction publique","Rassemblement National"),
 (52,"Boccaletti","Frédéric","Provence-Alpes-Côte dAzur","Var","7","cadre","Rassemblement National"),
 (53,"Laporte","Hélène","Nouvelle-Aquitaine","Lot-et-Garonne","2","Analyste bancaire","Rassemblement National"),
 (54,"Lottiaux","Philippe","Provence-Alpes-Côte dAzur","Var","4","Cadre de la fonction publique","Rassemblement National"),
 (55,"Houssin","Timothée","Normandie","Eure","5","Cadre ","Rassemblement National"),
 (56,"Galzy","Stéphanie","Occitanie","Hérault","5","Employé administratif dentreprise","Rassemblement National"),
 (57,"Da Conceicao Carvalho","Nathalie","Ile-de-France","Essonne","2","Profession libérale","Rassemblement National"),
 (58,"Muller","Serge","Nouvelle-Aquitaine","Dordogne","2","Profession intermédiaire de la santé et du travail social ","Rassemblement National"),
 (59,"Falcon","Frédéric","Occitanie","Aude","2","Commerçant et assimilé ","Rassemblement National"),
 (60,"Lavalette","Laure","Provence-Alpes-Côte dAzur","Var","2","cadre","Rassemblement National"),
 (61,"Chenu","Sébastien","Hauts-de-France","Nord","19","Conseiller en communication","Rassemblement National"),
 (62,"Catteau","Victor","Hauts-de-France","Nord","5","Juriste","Rassemblement National"),
 (63,"Sabatini","Anaïs","Occitanie","Pyrénées-Orientales","2","Avocate","Rassemblement National"),
 (64,"Tanguy","Jean-Philippe","Hauts-de-France","Somme","4","Cadre administratif et commercial dentreprise","Rassemblement National"),
 (65,"de Fournas","Grégoire","Nouvelle-Aquitaine","Gironde","5","Viticulteur","Rassemblement National"),
 (67,"Grenon","Daniel","Bourgogne-Franche-Comté","Yonne","1","Ancien artisan, commerçant, chef dentreprise","Rassemblement National"),
 (68,"Auzanot","Bénédicte","Provence-Alpes-Côte dAzur","Vaucluse","2","cadre","Rassemblement National"),
 (69,"Jolly","Alexis","Auvergne-Rhône-Alpes","Isère","6","Commerçant et assimilé","Rassemblement National"),
 (70,"Gillet","Yoann","Occitanie","Gard","1","Cadre de la fonction publique","Rassemblement National"),
 (71,"Roullaud","Béatrice","Ile-de-France","Seine-et-Marne","6","Profession libérale","Rassemblement National"),
 (72,"Dogor-Such","Sandrine","Occitanie","Pyrénées-Orientales","3","Préparatrice en pharmacie","Rassemblement National"),
 (73,"Lopez-Liguori","Aurélien","Occitanie","Hérault","7","Attaché parlementaire","Rassemblement National"),
 (74,"Bordes","Pascale","Occitanie","Gard","3","Profession libérale ","Rassemblement National"),
 (75,"Engrand","Christine","Hauts-de-France","Pas-de-Calais","6","Cadre administratif et commercial dentreprise","Rassemblement National"),
 (76,"Loubet","Alexandre","Grand Est","Moselle","7","Cadre dentreprise","Rassemblement National"), 
 (77,"Paris","Mathilde","Centre-Val de Loire","Loiret","3","Chef dentreprise de 10 salariés ou plus ","Rassemblement National"),
 (78,"Ballard","Philippe","Hauts-de-France","Oise","2","Ancien journaliste","Rassemblement National"),
 (79,"Robert-Dehault","Laurence","Grand Est","Haute-Marne","2","Profession libérale ","Rassemblement National"),
 (80,"Odoul","Julien","Bourgogne-Franche-Comté","Yonne","3","Collaborateur parlementaire","Rassemblement National"),
 (81,"Taverne","Michaël","Hauts-de-France","Nord","12","Policier et militaire","Rassemblement National"),
 (82,"Frappé","Thierry","Hauts-de-France","Pas-de-Calais","10","Profession libérale","Rassemblement National"),
 (83,"Gonzalez","José","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","10","Ancien employé","Rassemblement National"),
 (84,"Cousin","Annick","Nouvelle-Aquitaine","Lot-et-Garonne","3","Agent administratif hospitalier","Rassemblement National"),
 (85,"Guiniot","Michel","Hauts-de-France","Oise","6","Ancien cadre","Rassemblement National"),
 (86,"Tivoli","Lionel","Provence-Alpes-Côte dAzur","Alpes-Maritimes","2","Chef dentreprise de 10 salariés ou plus","Rassemblement National"),
 (87,"Girard","Christian","Provence-Alpes-Côte dAzur","Alpes-de-Haute-Provence","1","Ancien cadre","Rassemblement National"),
 (88,"Baubry","Romain","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","15","Policier et militaire","Rassemblement National"),
 (89,"Beaurain","José","Hauts-de-France","Aisne","4","Artisan","Rassemblement National");
 
CREATE TABLE ren(id_ren int,Nom_ren VARCHAR(50),Prénom_ren VARCHAR(0),Région_ren VARCHAR(50),Département-ren VARCHAR(50),circonscription-ren VARCHAR(50),Profession_ren VARCHAR(50),Groupe_ren VARCHAR(50));
INSERT INTO ren (id_ren,Nom_ren,Prénom_ren,Région_ren,Département_ren,circonscription_ren,Profession_ren,Groupe_ren)
  values
  (1,"Panosyan-Bouvet","Astrid","Ile-de-France","Paris","4","Cadre administratif et commercial dentreprise","Renaissance"),
 (2,"Le Feur","Sandrine","Bretagne","Finistère","4","Agriculteur-propriétaire exploitant","Renaissance"),
 (3,"Perrot","Patrice","Bourgogne-Franche-Comté","Nièvre","2","Industriel-Chef dentreprise","Renaissance"),
 (4,"Amiel","David","Ile-de-France","Paris","13","Sans profession déclarée","Renaissance"),
 (5,"Heydel Grillere","Laurence","Auvergne-Rhône-Alpes","Ardèche","2","Ingénieur agronome","Renaissance"),
 (6,"Vidal","Annie","Normandie","Seine-Maritime","2","Retraitée de la fonction publique hospitalière","Renaissance"),
 (7,"Rudigoz","Thomas","Auvergne-Rhône-Alpes","Rhône","1","Sans profession déclarée","Renaissance"),
 (8,"Belhaddad","Belkhir","Grand Est","Moselle","1","Industriel-Chef dentreprise","Renaissance"),
 (9,"Bordat","Benoît","Bourgogne-Franche-Comté","Côte-dOr","2","Conseiller foncier agricole","Renaissance"),
 (10,"Reda","Robin","Ile-de-France","Essonne","7","consultant","Renaissance"),
 (3,"Mendes","Ludovic","Grand Est","Moselle","2","Cadre supérieur (secteur privé)","Renaissance"),
 (14,"Hai","Nadia","Ile-de-France","Yvelines","7","Conseil en gestion de patrimoine","Renaissance"),
 (15,"Lauzzana","Michel","Nouvelle-Aquitaine","Lot-et-Garonne","1","Médecin","Renaissance"),
 (16,"Chandler","Émilie","Ile-de-France","Val-dOise","1","Profession libérale","Renaissance"),
 (17,"Sertin","Freddy","Normandie","Calvados","6","Directeur Général dun établissement de santé","Renaissance"),
 (18,"Boyer","Pascale","Provence-Alpes-Côte dAzur","Hautes-Alpes","1","Contremaître, agent de maîtrise","Renaissance"),
 (19,"Le Vigoureux","Fabrice","Normandie","Calvados","1","Professeur des Universités","Renaissance"),
 (20,"Lebec","Marie","Ile-de-France","Yvelines","4","Consultante en affaires publiques","Renaissance"),
 (21,"Gouffier Valente","Guillaume","Ile-de-France","Val-de-Marne","6","Manager public","Renaissance"),
 (22,"Guévenoux","Marie","Ile-de-France","Essonne","9","Collaborateur politique","Renaissance"),
 (23,"Liso","Brigitte","Hauts-de-France","Nord","4","Commerçant","Renaissance"),
 (24,"Ledoux","Vincent","Hauts-de-France","Nord","10","Professeur","Renaissance"),
 (25,"Saint-Paul","Laetitia","Pays de la Loire","Maine-et-Loire","4","Officier de larmée de Terre","Renaissance"),
 (26,"Yadan","Caroline","Ile-de-France","Paris","3","avocat","Renaissance"),
 (27,"Lakrafi","Amélia","Français établis hors de France","Français établis hors de France","10","Chef dentreprise","Renaissance"),
 (28,"Vignon","Corinne","Occitanie","Haute-Garonne","3","Cadre supérieur (secteur privé)","Renaissance"),
 (29,"Vojetta","Stéphane","Français établis hors de France","Français établis hors de France","5","Entrepreneur","Renaissance"),
 (30,"Hugues","Servane","Auvergne-Rhône-Alpes","Isère","1","Professeur des écoles","Renaissance"),
 (31,"Batut","Xavier","Normandie","Seine-Maritime","10","Autre cadre (secteur privé)","Renaissance"),
 (32,"Chenevard","Yannick","Provence-Alpes-Côte dAzur","Var","1","Profession libérale","Renaissance"),
 (33,"Ardouin","Jean-Philippe","Nouvelle-Aquitaine","Charente-Maritime","3","Chef dentreprise","Renaissance"),
 (34,"Riotton","Véronique","Auvergne-Rhône-Alpes","Haute-Savoie","1","Consultante-Coach en Ressources Humaines","Renaissance"),
 (35,"Kasbarian","Guillaume","Centre-Val de Loire","Eure-et-Loir","1","Cadre supérieur (secteur privé)","Renaissance"),
 (36,"Guichard","Claire","Ile-de-France","Hauts-de-Seine","10","Sans profession déclarée","Renaissance"),
 (37,"Calvez","Céline","Ile-de-France","Hauts-de-Seine","5","Consultante communication","Renaissance"),
 (38,"Izard","Alexis","Ile-de-France","Essonne","3","Cadre administratif et commercial dentreprise","Renaissance"),
 (39,"Errante","Sophie","Pays de la Loire","Loire-Atlantique","10","Industriel-Chef dentreprise","Renaissance"),
 (40,"Thevenot","Prisca","Ile-de-France","Hauts-de-Seine","8","collaboratrice parlementaire","Renaissance"),
 (41,"Maquet","Jacqueline","Hauts-de-France","Pas-de-Calais","2","Directrice de mission","Renaissance"),
 (42,"Bregeon","Maud","Ile-de-France","Hauts-de-Seine","13","Ingénieur et cadre technique dentreprise","Renaissance"),
 (43,"Dubré-Chirat","Nicole","Pays de la Loire","Maine-et-Loire","6","Retraitée de la fonction publique hospitalière et chargée de formation","Renaissance"),
 (44,"Lemoine","Patricia","Ile-de-France","Seine-et-Marne","5","Directrice de cabinet","Renaissance"),
 (45,"Berete","Fanta","Ile-de-France","Paris","12","Directrice projets","Renaissance"),
 (46,"Cazeneuve","Pierre","Ile-de-France","Hauts-de-Seine","7","Cadre de la fonction publique","Renaissance"),
 (47,"Spillebout","Violette","Hauts-de-France","Nord","9","Cadre administratif et commercial dentreprise","Renaissance"),
 (48,"Midy","Paul","Ile-de-France","Essonne","5","Chef dentreprise de 10 salariés ou plus","Renaissance"),
 (49,"Janvier","Caroline","Centre-Val de Loire","Loiret","2","Autre cadre (secteur privé)","Renaissance"),
 (50,"Peyron","Michèle","Ile-de-France","Seine-et-Marne","9","Autre cadre (secteur privé)","Renaissance"),
 (51,"Marchive","Bastien","Nouvelle-Aquitaine","Deux-Sèvres","1","Juriste","Renaissance"),
 (52,"Fait","Philippe","Hauts-de-France","Pas-de-Calais","4","Professeur des écoles, instituteur et assimilé","Renaissance"),
 (53,"Poulliat","Éric","Nouvelle-Aquitaine","Gironde","6","Fonctionnaire de catégorie B","Renaissance"),
 (54,"Chassaniol","Clara","Ile-de-France","Paris","7","Collaboratrice parlementaire","Renaissance"),
 (55,"Agresti-Roubache","Sabrina","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","1","Profession libérale","Renaissance"),
 (56,"Vuilletet","Guillaume","Ile-de-France","Val-dOise","2","Cadre supérieur (secteur privé)","Renaissance"),
 (57,"Bataillon","Quentin","Auvergne-Rhône-Alpes","Loire","1","Cadre administratif et commercial dentreprise","Renaissance"),
 (58,"Vignal","Patrick","Occitanie","Hérault","9","Industriel-Chef dentreprise","Renaissance"),
 (59,"Delpech","Julie","Pays de la Loire","Sarthe","1","Chargée de communication","Renaissance"),
 (60,"Le Meur","Annaïg","Bretagne","Finistère","1","Autre profession libérale","Renaissance"),
 (61,"Maillard","Sylvain","Ile-de-France","Paris","1","Industriel-Chef dentreprise","Renaissance"),
 (62,"Cazeneuve","Jean-René","Occitanie","Gers","1","Ingénieur","Renaissance"),
 (63,"Brulebois","Danielle","Bourgogne-Franche-Comté","Jura","1","Retraitée de lenseignement","Renaissance"),
 (64,"Dunoyer","Philippe","Nouvelle-Calédonie","Nouvelle-Calédonie","1","Fonctionnaire de catégorie A","Renaissance"),
 (65,"Bothorel","Éric","Bretagne","Côtes-dArmor","5","Cadre supérieur (secteur privé)","Renaissance"),
 (66,"Fiévet","Jean-Marie","Nouvelle-Aquitaine","Deux-Sèvres","3","Fonctionnaire de catégorie B","Renaissance"),
 (67,"Panonacle","Sophie","Nouvelle-Aquitaine","Gironde","8","Sans profession déclarée","Renaissance"),
 (68,"Travert","Stéphane","Normandie","Manche","3","Cadre secteur privé","Renaissance"),
 (69,"Ferracci","Marc","Français établis hors de France","Français établis hors de France",6,"Professeur, profession scientifique","Renaissance"),
 (70,"Buffet","Françoise","Grand Est","Bas-Rhin","4","Ancien artisan, commerçant, chef dentreprise","Renaissance"),
 (71,"Decodts","Christine","Hauts-de-France","Nord","13","Ancien cadre","Renaissance"),
 (72,"Bergé","Aurore","Ile-de-France","Yvelines","10","Cadre supérieur (secteur privé)","Renaissance"),
 (73,"Clapot","Mireille","Auvergne-Rhône-Alpes","Drôme","1","Cadre supérieur (entreprises publiques)","Renaissance"),
 (74,"Marsaud","Sandra","Nouvelle-Aquitaine","Charente","2","Cadre (entreprises publiques)","Renaissance"),
 (75,"Jacques","Jean-Michel","Bretagne","Morbihan","6","Infirmier des forces spéciales","Renaissance"),
 (76,"Petel","Anne-Laurence","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","14","Chargée des relations extérieures - secteur télécom","Renaissance"),
 (78,"Miller","Laure","Grand Est","Marne","2","Avocate","Renaissance"),
 (79,"Martin","Didier","Bourgogne-Franche-Comté","Côte-dOr","1","Neuroradiologue","Renaissance"),
 (80,"Pouzyreff","Natalia","Ile-de-France","Yvelines","6","Ingénieure","Renaissance"),
 (81,"Tiegna","Huguette","Occitanie","Lot","2","Docteur, Ingénieur Recherche et Dévelopement","Renaissance"),
 (82,"Piron","Béatrice","Ile-de-France","Yvelines","3","Chef dentreprise","Renaissance"),
 (83,"Girardin","Éric","Grand Est","Marne","3","Industriel-Chef dentreprise","Renaissance"),
 (84,"Grelier","Jean-Carles","Pays de la Loire","Sarthe","5","Avocat","Renaissance"),
 (85,"Dupont","Stella","Pays de la Loire","Maine-et-Loire","2","Comptable","Renaissance"),
 (86,"Le Gac","Didier","Bretagne","Finistère","3","Profession rattachée à lenseignement","Renaissance"),
 (87,"Lefèvre","Mathieu","Ile-de-France","Val-de-Marne","5","Cadre de la fonction publique","Renaissance"),
 (88,"Cazenave","Thomas","Nouvelle-Aquitaine","Gironde","1","Cadre de la fonction publique","Renaissance"),
 (89,"Adam","Damien","Normandie","Seine-Maritime","1","Cadre supérieur (secteur privé)","Renaissance"),
 (90,"Giraud","Joël","Provence-Alpes-Côte dAzur","Hautes-Alpes","2","Administrateur civil hors-classe","Renaissance"),
 (91,"Melchior","Graziella","Bretagne","Finistère","5","Professeure agrégée","Renaissance"),
 (92,"Anglade","Pieyre-Alexandre","Français établis hors de France","Français établis hors de France",4,"Agent contractuel au Parlement européen","Renaissance"),
 (93,"Haddad","Benjamin","Ile-de-France","Paris","14","Professeur, profession scientifique","Renaissance"),
 (94,"Maillart-Méhaignerie","Laurence","Bretagne","Ille-et-Vilaine","2","Chef entreprise","Renaissance"),
 (95,"Lacresse","Emmanuel","Grand Est","Meurthe-et-Moselle","2","Cadre de la fonction publique","Renaissance"),
 (96,"Cristol","Laurence","Occitanie","Hérault","3","Médecin spécialiste en onco-gériatrie","Renaissance"),
 (97,"Khattabi","Fadila","Bourgogne-Franche-Comté","Côte-dOr","3","Professeur danglais CFA","Renaissance"),
 (98,"Tanguy","Liliana","Bretagne","Finistère","7","Cadre supérieur du secteur public","Renaissance"),
 (99,"Dirx","Benjamin","Bourgogne-Franche-Comté","Saône-et-Loire","1","Industriel-Chef dentreprise","Renaissance"),
 (100,"Mournet","Benoit","Occitanie","Hautes-Pyrénées","2","Cadre de la fonction publique","Renaissance"),
 (101,"Terlier","Jean","Occitanie","Tarn","3","Avocat","Renaissance"),
 (102,"Pompili","Barbara","Hauts-de-France","Somme","2","Assistante parlementaire","Renaissance"),
 (103,"Parmentier-Lecocq","Charlotte","Hauts-de-France","Nord","6","Industriel-Chef dentreprise","Renaissance"),
 (104,"Royer-Perreaut","Lionel","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","6","Cadre","Renaissance"),
 (105,"Brugnera","Anne","Auvergne-Rhône-Alpes","Rhône","4","Fonctionnaire de catégorie A","Renaissance"),
 (106,"Braun-Pivet","Yaël","Ile-de-France","Yvelines","5","Avocate","Renaissance"),
 (107,"Klinkert","Brigitte","Grand Est","Haut-Rhin","1","Ancien cadre","Renaissance"),
 (108,"Gérard","Raphaël","Nouvelle-Aquitaine","Charente-Maritime","4","Cadre supérieur (secteur privé)","Renaissance"),
 (109,"Belhamiti","Mounir","Pays de la Loire","Loire-Atlantique","1","Ingénieur chef de projet digital","Renaissance"),
 (110,"Paris","Didier","Bourgogne-Franche-Comté","Côte-dOr","5","Cadre supérieur (secteur privé) ","Renaissance"),
 (111,"Rodwell","Charles","Ile-de-France","Yvelines","1","Cadre de la fonction publique","Renaissance"),
 (112,"Masséglia","Denis","Pays de la Loire","Maine-et-Loire","5","Ingénieur Arts et métiers","Renaissance"),
 (113,"Causse","Lionel","Nouvelle-Aquitaine","Landes","2","Autre cadre (secteur privé)","Renaissance"),
 (114,"Holroyd","Alexandre","Français établis hors de France","Français établis hors de France","3","Cadre","Renaissance"),
 (115,"Weissberg","Christopher","Français établis hors de France","Français établis hors de France","1","Chef dentreprise","Renaissance"),
 (116,"Rixain","Marie-Pierre","Ile-de-France","Essonne","4","Consultante en communication","Renaissance"),
 (117,"Woerth","Éric","Hauts-de-France","Oise","4","Associé dans un cabinet daudit international","Renaissance"),
 (118,"Rist","Stéphanie","Centre-Val de Loire","Loiret","1","Médecin","Renaissance"),
 (119,"Mazars","Stéphane","Occitanie","Aveyron","1","Avocat","Renaissance"),
 (120,"Ghomi","Hadrien","Ile-de-France","Seine-et-Marne","8","Cadre de la fonction publique","Renaissance"),
 (121,"Vuibert","Lionel","Grand Est","Ardennes","1","Cadre dentreprise de 10 salariés ou plus","Renaissance"),
 (122,"Iborra","Monique","Occitanie","Haute-Garonne","6","Retraitée de la Fonction publique","Renaissance"),
 (123,"Givernet","Olga","Auvergne-Rhône-Alpes","Ain","3","Ingénieure aéronautique","Renaissance"),
 (124,"Le Nabour","Christine","Bretagne","Ille-et-Vilaine","5","Employée (secteur privé)","Renaissance"),
 (124,"Armand","Antoine","Auvergne-Rhône-Alpes","Haute-Savoie","2","Cadre de la fonction publique","Renaissance"),
 (125,"Rebeyrotte","Rémy","Bourgogne-Franche-Comté","Saône-et-Loire","3","Professeur déconomie","Renaissance"),
 (126,"Buchou","Stéphane","Pays de la Loire","Vendée","3","Cadre supérieur (secteur privé)","Renaissance"),
 (127,"Le Grip","Constance","Ile-de-France","Hauts-de-Seine","6","Conseillère parlementaire","Renaissance"),
 (128,"Lovisolo","Jean-François","Provence-Alpes-Côte dAzur","Vaucluse","5","Maire","Renaissance"),
 (129,"Goetschy-Bolognese","Charlotte","Grand Est","Haut-Rhin","5","Chargée de gestion administrative","Renaissance"),
 (130,"Abad","Damien","Auvergne-Rhône-Alpes","Ain","5","Sans profession déclarée","Renaissance"),
 (131,"Pellerin","Emmanuel","Ile-de-France","Hauts-de-Seine","9","Profession libérale","Renaissance"),
 (132,"Abadie","Caroline","Auvergne-Rhône-Alpes","Isère","8","Industriel-Chef entreprise","Renaissance"),
 (133,"Cormier-Bouligeon","François","Centre-Val de Loire","Cher","1","Conseiller ministériel","Renaissance"),
 (134,"Olive","Karl","Ile-de-France","Yvelines","12","Chef dentreprise","Renaissance"),
 (135,"Bouyx","Bertrand","Normandie","Calvados","5","Pharmacien","Renaissance"),
 (136,"Margueritte","Louis","Bourgogne-Franche-Comté","Saône-et-Loire","5","Cadre de la fonction publique","Renaissance"),
 (137,"Guillemard","Philippe","Grand Est","Meurthe-et-Moselle","1","Avocat","Renaissance"),
 (138,"Roseren","Xavier","Auvergne-Rhône-Alpes","Haute-Savoie","6","Commerçant","Renaissance"),
 (139,"Alauzet","Éric","Bourgogne-Franche-Comté","Doubs","2","Médecin","Renaissance"),
 (140,"Rousset","Jean-François","Occitanie","Aveyron","3","Chirurgien","Renaissance"),
 (141,"Pacquot","Nicolas","Bourgogne-Franche-Comté","Doubs","3","Ingénieur et cadre technique dentreprise","Renaissance"),
 (142,"Pont","Jean-Pierre","Hauts-de-France","Pas-de-Calais","5","Médecin","Renaissance"),
 (143,"Le Peih","Nicole","Bretagne","Morbihan","3","Agricultrice","Renaissance"),
 (144,"Zulesi","Jean-Marc","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","8","Autre cadre (secteur privé)","Renaissance"),
 (145,"Sorre","Bertrand","Normandie","Manche","2","Enseignant 1er degré-directeur décole (en disponibilité)","Renaissance"),
 (146,"Fugit","Jean-Luc","Auvergne-Rhône-Alpes","Rhône","11","Professeur de faculté","Renaissance"),
 (147,"Studer","Bruno","Grand Est","Bas-Rhin","3","Professeur du secondaire et technique","Renaissance"),
 (148,"Marion","Christophe","Centre-Val de Loire","Loir-et-Cher","3","Délégué général du Comité des travaux historiques et scientifiques","Renaissance"),
 (149,"Bouloux","Chantal","Bretagne","Côtes-dArmor","2","Directrice dEhpad","Renaissance"),
 (150,"Da Silva","Dominique","Ile-de-France","Val-dOise","7","Industriel-Chef dentreprise","Renaissance"),
 (151,"Brosse","Anthony","Centre-Val de Loire","Loiret","5","Profession intermédiaire de la santé et du travail social","Renaissance"),
 (152,"Pitollat","Claire","Provence-Alpes-Côte dAzur","Bouches-du-Rhône","2","Ingénieure","Renaissance"),
 (153,"Valence","David","Grand Est","Vosges","2","Professeur agrégé","Renaissance"),
 (154,"Henriet","Pierre","Pays de la Loire","Vendée","5","Professeur du secondaire et technique","Renaissance"),
 (155,"Métayer","Lysiane","Bretagne","Morbihan","5","Cadre de la fonction publique","Renaissance"),
 (156,"Labaronne","Daniel","Centre-Val de Loire","Indre-et-Loire","2","Retraité de lenseignement supérieur","Renaissance"),
 (157,"Rilhac","Cécile","Ile-de-France","Val-dOise","3","Profession rattachée à lenseignement","Renaissance"),
 (158,"Houlié","Sacha","Nouvelle-Aquitaine","Vienne","2","Avocat","Renaissance"),
(159,"Meynier-Millefert","Marjolaine","Auvergne-Rhône-Alpes","Isère","10","Conseillère en stratégie des organisations","Renaissance"),
 (160,"Genetet","Anne","Français établis hors de France","Français établis hors de France","11","Médecin","Renaissance"),
 (161,"Boudié","Florent","Nouvelle-Aquitaine","Gironde","10","Cadre supérieur du secteur public","Renaissance"),
 (162,"Haury","Yannick","Pays de la Loire","Loire-Atlantique","9","Pharmacien","Renaissance"),
 (163,"Descrozaille","Frédéric","Ile-de-France","Val-de-Marne","1","Autre cadre (secteur privé)","Renaissance"),
 (164,"Colboc","Fabienne","Centre-Val de Loire","Indre-et-Loire","4","Industriel-Chef dentreprise","Renaissance"),
 (165,"Le Gendre","Gilles","Ile-de-France","Paris","2","Industriel-Chef dentreprise","Renaissance"),
 (166,"Sorez","Philippe","Occitanie","Hérault","1","Cadre commercial dans lindustrie et le bâtiment","Renaissance"),
 (168,"Metzdorf","Nicolas","Nouvelle-Calédonie","Nouvelle-Calédonie","2","Ingénieur et cadre technique dentreprise","Renaissance"),
 (169,"Lavergne","Pascal","Nouvelle-Aquitaine","Gironde","12","Ingénieur-Agriculteur","Renaissance"),
(170,"Gassilloud","Thomas","Auvergne-Rhône-Alpes","Rhône","10","Industriel-Chef dentreprise","Renaissance"),
 (171,"Tanzilli","Sarah","Auvergne-Rhône-Alpes","Rhône","13","Cadre administratif","Renaissance"),
 (172,"Seo","Mikaele","Wallis-et-Futuna","Wallis-et-Futuna","1","Profession intermédiaire administrative de la fonction publique","Renaissance"),
 (173,"Sitzenstuhl","Charles","Grand Est","Bas-Rhin","5","Cadre de la fonction publique","Renaissance");
 CREATE TABLE sonupes(id_sonupes int,Nom_sonupes VARCHAR(50),Prénom_sonupes VARCHAR(50),Région_sonupes VARCHAR(50),Département_sonupes VARCHAR(50),circonscription_sonupes VARCHAR(50),Profession_sonupes VARCHAR(50),Groupe_sonupes VARCHAR(50));
INSERT INTO sonupes (id_sonupes,Nom_sonupes,Prénom_sonupes,Région_sonupes,Département_sonupes,circonscription_sonupes,Profession_sonupes,Groupe_sonupes)
 values
 (1,"Hajjar","Johnny","Martinique","Martinique","3","Professeur du second degré","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
 (2,"Rabault","Valérie","Occitanie","Tarn-et-Garonne","1","Ingénieure","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
 (3,"Jourdan","Chantal","Normandie","Orne","1","Psychologue","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
 (4,"Brun","Philippe","Normandie","Eure","4","Magistrat administratif","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
 (5,"Pires Beaune","Christine","Auvergne-Rhône-Alpes","Puy-de-Dôme","2","Fonctionnaire de catégorie A","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
 (6,"Faure","Olivier","Ile-de-France","Seine-et-Marne","11","Cadre supérieur (secteur privé)","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
 (7,"Thomin","Mélanie","Bretagne","Finistère","6","Professeur, profession scientifique","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
 (8,"Rouaux","Claudia","Bretagne","Ille-et-Vilaine","3","Gestionnaire à lINRAE","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
 (9,"Leseul","Gérard","Normandie","Seine-Maritime","5","Cadre dentreprise / enseignant universitaire","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(10,"David","Alain","Nouvelle-Aquitaine","Gironde","4","Ingénieur","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(11,"Vallaud","Boris","Nouvelle-Aquitaine","Landes","3","Fonctionnaire de catégorie A","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(12,"Baptiste","Christian","Guadeloupe","Guadeloupe","2","Directeur dassociation","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(13,"Untermaier","Cécile","Bourgogne-Franche-Comté","Saône-et-Loire","4","Fonctionnaire des grands corps de lÉtat","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(14,"Saulignac","Hervé","Auvergne-Rhône-Alpes","Ardèche","1","Cadre (entreprises publiques)","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(15,"Bouloux","Mickaël","Bretagne","Ille-et-Vilaine","8","Ingénieur et cadre technique dentreprise","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(16,"Keloua Hachi","Fatiha","Ile-de-France","Seine-Saint-Denis","8","Professeur, profession scientifique","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(17,"Karamanli","Marietta","Pays de la Loire","Sarthe","2","Professeur dans lenseignement supérieur","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(18,"Delautrette","Stéphane","Nouvelle-Aquitaine","Haute-Vienne","2","Ingénieur dans le domaine de lenvironnement","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(19,"Vicot","Roger","Hauts-de-France","Nord","11","Intervenant en communication","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(20,"Garot","Guillaume","Pays de la Loire","Mayenne","1","Cadre administratif","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(21,"Echaniz","Inaki","Nouvelle-Aquitaine","Pyrénées-Atlantiques","4","Cadre de la fonction publique","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(22,"Guedj","Jérôme","Ile-de-France","Essonne","6","Inspecteur général des Affaires sociales","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(23,"Califer","Elie","Guadeloupe","Guadeloupe","4","Ancien cadre","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(24,"Petit","Bertrand","Hauts-de-France","Pas-de-Calais","8","Personne diverse sans activité professionnelle de moins de 60 ans (sauf retraité","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(25,"Delaporte","Arthur","Normandie","Calvados","2","Professeur, profession scientifique","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(26,"Potier","Dominique","Grand Est","Meurthe-et-Moselle","5","Agriculteur","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(27,"Battistel","Marie-Noëlle","Auvergne-Rhône-Alpes","Isère","4","Autre cadre (secteur privé)","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(28,"Aviragnet","Joël","Occitanie","Haute-Garonne","8","Directeur dun établissement pour lenfance handicapée","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(29,"Naillet","Philippe","Réunion","Réunion","1","Inspecteur assurance-vie","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(30,"Pic","Anna","Normandie","Manche","4","Professeur, profession scientifique","Socialistes et apparentés (membre de l’intergroupe NUPES)"),
(31,"Santiago","Isabelle","Ile-de-France","Val-de-Marne","9","Cadre territorial","Socialistes et apparentés (membre de l’intergroupe NUPES)");
